version: "3.9"
services:
  app_gateway:
    image: prestoshat-backend/gateway:1.0
    container_name: app_gateway
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment: 
      SPRING_APPLICATION_JSON: '{
        "env": "P"  
        }' 
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge